### PR TITLE
Optimized speed by .bind method. Code cleanup.

### PR DESCRIPTION
**Pull request by gloryknight**
Use of bind method should increase speed of both compression and decompression. emptyString variable reduces size of minified file. getBitStream function reduces size of minified file. Use hexadecimal numbers for consistency. Use single quotes everywhere.

### CODE REVIEW

**Comment by JobLeonard** [comment]
Nice!

I just [checked MDN for backwards compatibility of `bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Specifications), and it was introduced in ES5. Sadly, that makes it a no-no for the plain lz-string code, which should support pre-ES5.

However, I already created a (not yet committed) ES6 version. I'll include your modifications. Since browsers typically add support first, optimisations later, limiting `bind` to ES6 compatible browsers is probably the safer bet anyway.

Of course the other code clean-up looks fine :+1:

**Comment by JobLeonard** [comment]
Looks like `bind` does not improve performance for compression. If might for decompression, since it avoids a closure:

Chrome:
image

Firefox:
image

https://run.perf.zone/view/LZString-variants-15-07-2018-minified-compress-documentbodyinnerHTML-1531692683617

**Comment by gloryknight** [comment]
Thanks for the benchmarks. I do agree ES6 version for modern browsers is good idea. Progress looks good.

BTW: speaking of size. I was able to push the decompress function down to 450 bytes with minor performance decay (this could be used in size critical applications like self-unpacking pages or something like this):

    function Ld(a){var l,q,b=String.fromCharCode,d=a.length,e=a.charCodeAt.bind(a),f=16,g='',h=[g,g,g],i=4,j=4,k=3,m=[],n=0,o=2,p=0,r=e(0),s=f,t=1,u=()=>{for(;p!=o;)n+=(1&r>>--s)<<p++,0==s&&(s=f,r=e(t++))};for(u(),o=8*n+8,n=p=0,u(),q=b(n),h[3]=q,m.push(q);t<=d;){if(o=k,n=p=0,u(),2>n)o=8+8*n,n=p=0,u(),h[j]=b(n),n=j++,0==--i&&(i=1<<k++);else if(2==n)return m.join(g);l=n<h.length?h[n]:q+q.charAt(0),m.push(l),h[j++]=q+l.charAt(0),q=l,0==--i&&(i=1<<k++)}}

**Comment by gloryknight** [comment]
Update: 441 bytes:

function Ld(a){var l,r,b=String.fromCharCode,d=a.length,e=a.charCodeAt.bind(a),f=16,g='',h=[g,g,g],i=4,j=4,k=3,m=[],n=m.push,o=0,p=2,q=0,s=e(0),t=f,u=1,v=()=>{for(;q!=p;)o+=(1&s>>--t)<<q++,0==t&&(t=f,s=e(u++))};for(v(),p=8*o+8,o=q=0,r=b(o),h[3]=r,n(r);u<=d;){if(p=k,o=q=0,2>o)p=8+8*o,o=q=0,v(),h[j]=b(o),o=j++,0==--i&&(i=1<<k++);else if(2==o)return m.join(g);l=o<h.length?h[o]:r+r.charAt(0),n(l),h[j++]=r+l.charAt(0),r=l,0==--i&&(i=1<<k++)}}

**Comment by JobLeonard** [comment]
You might want to precede that piece of code with four spaces, now it interprets `*` as MarkDown

**Comment by gloryknight** [comment]
Thanks for the tip. Done.

**Comment by JobLeonard** [comment]
So I'm closing this pull request because of the aforementioned backwards compatibility. But when that ES6 module comes around...

**Pull request closed without merging**
